

CREATE TABLE SITE(SITE_ID INTEGER PRIMARY KEY AUTOINCREMENT, SITE_NAME VARCHAR(200) not null, SITE_ADDRESS varchar(500), CREATED_DATE DATETIME)


CREATE TABLE LABOUR_WORK_TYPE (LABOUR_WORK_ID INTEGER PRIMARY KEY AUTOINCREMENT, LABOUR_WORK_NAME varchar(100))
CREATE TABLE MaterialType (Material_Id INTEGER PRIMARY KEY AUTOINCREMENT, MATERIAL_NAME varchar(100))
CREATE TABLE QUANTITY_UNIT(UNIT_ID INTEGER PRIMARY KEY AUTOINCREMENT, UNIT_NAME varchar(50))
CREATE TABLE DEBIT_CREDIT_ENTITIES(ENTITY_ID INTEGER  PRIMARY KEY AUTOINCREMENT, ENTITY_NAME VARCHAR(50))
CREATE TABLE PAYMENT_MODE(PAYMENT_MODE_ID INTEGER  PRIMARY KEY AUTOINCREMENT, PAYMENT_MODE_NAME VARCHAR(50))

CREATE TABLE MATERIAL_PURCHASE_DETAIL (
    PURCHASE_ID   INTEGER       PRIMARY KEY AUTOINCREMENT,
    VENDOR_ID     INTEGER       NOT NULL,
    MATERIAL_TYPE_ID INTEGER,
    BILL_NUMBER   VARCHAR (10)  NOT NULL,
    BILL_DATE     DATETIME,
    BILL_AMOUNT   REAL,
    QUANTITY      NUMBER (5),
    UNIT_ID INTEGER,
    REMARK        VARCHAR (500),
    SITE_ID       INTEGER,
    CREATED_DATE  DATETIME,
    FOREIGN KEY (MATERIAL_TYPE_ID) REFERENCES MaterialType(Material_Id) ON DELETE CASCADE,
    FOREIGN KEY (UNIT_ID) REFERENCES QUANTITY_UNIT(UNIT_ID) ON DELETE CASCADE,
    FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR (VENDOR_ID) ON DELETE CASCADE,
    FOREIGN KEY (SITE_ID) REFERENCES SITE (SITE_ID) ON DELETE CASCADE
)



CREATE TABLE CUSTOMER (
CUSTOMER_ID INTEGER Primary Key AUTOINCREMENT,
 CUSTOMER_NAME varchar(200) NOT NULL,
  MOBILE_NUMBER varchar(25),
   PURCHASE_DATE DATETIME, 
   HOUSE_NUMBER varchar(20) NOT NULL, 
   HOUSE_COST REAL, 
   EXTRA_WORK varchar(200), 
   EXTRA_COST REAL, 
   CREATED_DATE DATETIME,
   SITE_ID INTEGER NOT NULL, 
   Foreign Key (SITE_ID) REFERENCES SITE(SITE_ID) ON DELETE CASCADE )
   
   CREATE TABLE SUPERVISOR(
SUPERVISOR_ID INTEGER PRIMARY KEY AUTOINCREMENT,
 SUPERVISOR_NAME varchar(200) NOT NULL, 
 DESCRIPTION varchar(500), 
 Salary REAL, 
 CREATED_DATE DATETIME,
 SITE_ID INTEGER NOT NULL, 
 Foreign Key (SITE_ID) REFERENCES SITE(SITE_ID) ON DELETE CASCADE )
 
 CREATE TABLE SITE(
SITE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
SITE_NAME varchar(200),
SITE_ADDRESS varchar(300),
CREATED_DATE DATETIME)

CREATE TABLE CONTRACTOR(
CONTRACTOR_ID INTEGER PRIMARY KEY AUTOINCREMENT,
CONTRACTOR_NAME VARCHAR(200),
DESCRIPTION VARCHAR(500),
CREATED_DATE DATETIME)

CREATE TABLE VENDOR(
VENDOR_ID INTEGER PRIMARY KEY AUTOINCREMENT,
VENDOR_NAME VARCHAR(200),
ADDRESS VARCHAR(500),
REMARK varchar(500),
CREATED_DATE DATETIME)

CREATE TABLE LABOUR_PAYMENT(
LABOUR_PAYMENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
 CONTRACTOR_ID INTEGER NOT NULL,
 WORK_TYPE_ID INTEGER NOT NULL, 
 WORK_DETAIL varchar(300),
  WORK_DATE DATETIME, 
  PAYMENT REAL,
  REMARK varchar(500),
  SITE_ID INTEGER NOT NULL,
  CREATED_DATE DATETIME,
  FOREIGN KEY (WORK_TYPE_ID) REFERENCES LABOUR_WORK_TYPE(LABOUR_WORK_ID) ON DELETE CASCADE, 
FOREIGN KEY (CONTRACTOR_ID) REFERENCES CONTRACTOR(CONTRACTOR_ID) ON DELETE CASCADE,
FOREIGN KEY (SITE_ID) REFERENCES SITE(SITE_ID) ON DELETE CASCADE)


CREATE TABLE DEBIT_CREDIT (PAYMENT_ID INTEGER  PRIMARY KEY AUTOINCREMENT, 
ENTITY_ID INTEGER,
ENTITY_TYPE_ID INTEGER,
DEBITAMOUNT REAL,
CREDITAMOUNT REAL, 
REMARK varchar(500), 
PAYMENT_DATE DATETIME,
PAYMENT_MODE_ID INTEGER,
SITE_ID INTEGER, 
FOREIGN KEY (ENTITY_TYPE_ID) REFERENCES DEBIT_CREDIT_ENTITIES(ENTITY_TYPE_ID) ON DELETE CASCADE, 
FOREIGN KEY (PAYMENT_MODE_ID) REFERENCES PAYMENT_MODE(PAYMENT_MODE_ID) ON DELETE CASCADE,
FOREIGN KEY (SITE_ID) REFERENCES SITE(SITE_ID) ON DELETE CASCADE
)



