PRAGMA writable_schema = ON;
UPDATE sqlite_master SET sql ='CREATE TABLE MATERIAL_PURCHASE_DETAIL (    PURCHASE_ID   INTEGER       PRIMARY KEY AUTOINCREMENT,    VENDOR_ID     INTEGER,    MATERIAL_TYPE_ID INTEGER,
    BILL_NUMBER   VARCHAR (10)  NOT NULL,
    BILL_DATE     DATETIME,
    BILL_AMOUNT   REAL,
    QUANTITY      NUMBER (5),
    UNIT_ID INTEGER,
    REMARK        VARCHAR (500),
    SITE_ID       INTEGER,
    CREATED_DATE  DATETIME,
    FOREIGN KEY (MATERIAL_TYPE_ID) REFERENCES MaterialType(Material_Id) ON DELETE CASCADE,
    FOREIGN KEY (UNIT_ID) REFERENCES QUANTITY_UNIT(UNIT_ID) ON DELETE CASCADE,
    FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR (VENDOR_ID) ON DELETE CASCADE,
    FOREIGN KEY (SITE_ID) REFERENCES SITE (SITE_ID) ON DELETE CASCADE
)' WHERE name = 'MATERIAL_PURCHASE_DETAIL';

UPDATE sqlite_master SET sql ='CREATE TABLE LABOUR_PAYMENT(
LABOUR_PAYMENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
 CONTRACTOR_ID INTEGER,
 WORK_TYPE_ID INTEGER NOT NULL, 
 WORK_DETAIL varchar(300),
  WORK_DATE DATETIME, 
  PAYMENT REAL,
  REMARK varchar(500),
  SITE_ID INTEGER NOT NULL,
  CREATED_DATE DATETIME,
  FOREIGN KEY (WORK_TYPE_ID) REFERENCES LABOUR_WORK_TYPE(WORK_TYPE_ID) ON DELETE CASCADE, 
FOREIGN KEY (CONTRACTOR_ID) REFERENCES CONTRACTOR(CONTRACTOR_ID) ON DELETE CASCADE,
FOREIGN KEY (SITE_ID) REFERENCES SITE(SITE_ID) ON DELETE CASCADE)' WHERE name = 'LABOUR_PAYMENT';

